name: Publish annotator docker images

on:
  # Trigger the workflow on push
  # but only for the master branch
  push:
    branches:
      - master


jobs:
  push_to_registry:
    name: Push annotator docker images to GitHub Packages
    runs-on: ubuntu-latest
    
    steps:
      - 
        name: Check out the repo
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.REGISTRY_TOKEN }}
      -
        name: copy env 
        run: cp example.env .env
      -
        name: Build and push annotator docker
        uses: docker/build-push-action@v2
        with:
          push: true
          file: ./Dockerfile
          tags: |
            ghcr.io/jimmylevell/annotator:latest
      -
       name: Deploy to Docker swarm
       uses: wshihadeh/docker-deployment-action@v2
       with:
          remote_docker_host: docker@5.9.138.216
          ssh_private_key: ${{ secrets.DOCKER_SSH_PRIVATE_KEY }}
          ssh_public_key: ${{ secrets.DOCKER_SSH_PUBLIC_KEY }}
          deployment_mode: docker-swarm
          pull_images_first: 'true'
          args: ghcr.io/jimmylevell/annotator:latest
